name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *" # 每天午夜自动更新一次
  workflow_dispatch: # 允许你手动点击按钮立刻更新

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Profile Summary Cards

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: main # 如果你的默认分支叫 master，请改成 master
